# Generated by Django 5.1.3 on 2024-12-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='db_pics/')),
                ('label', models.DecimalField(decimal_places=2, max_digits=5)),
                ('label_name', models.CharField(max_length=255)),
                ('add_date', models.DateField()),
            ],
        ),
    ]
