# Generated by Django 5.1.3 on 2024-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisdata',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
