# Generated by Django 5.1.3 on 2024-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_classify', '0002_alter_hisdata_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
