# Generated by Django 5.1.3 on 2024-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_classify', '0003_alter_hisdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisdata',
            name='label',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='hisdata',
            name='label_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
