# Generated by Django 5.1.3 on 2024-12-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_classify', '0004_alter_hisdata_label_alter_hisdata_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisdata',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
