# Generated by Django 5.1.3 on 2024-12-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_classify', '0007_remove_hisdata_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisdata',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
